package repository

import (
	"context"
	"time"
)

// PasswordResetToken represents a password reset token record.
type PasswordResetToken struct {
	ID        string
	UserID    string
	TokenHash string
	ExpiresAt time.Time
	Used      bool
	CreatedAt time.Time
}

// PasswordResetTokenRepository defines the interface for password reset token data access.
type PasswordResetTokenRepository interface {
	// Create inserts a new password reset token.
	// The ID is generated by PostgreSQL's uuidv7() function.
	Create(ctx context.Context, token *PasswordResetToken) error

	// FindByTokenHash finds an unused, unexpired token by its hash.
	FindByTokenHash(ctx context.Context, tokenHash string) (*PasswordResetToken, error)

	// MarkUsed marks a token as used.
	MarkUsed(ctx context.Context, id string) error

	// DeleteByUserID removes all tokens for a user (cleanup).
	DeleteByUserID(ctx context.Context, userID string) error
}
