package repository

import (
	"context"

	"harmoni-api/internal/domain/entity"

	"github.com/jackc/pgx/v5"
)

// TenantRepository defines the interface for tenant data access.
type TenantRepository interface {
	// Create inserts a new tenant into the database.
	// The ID is generated by PostgreSQL's uuidv7() function.
	Create(ctx context.Context, tenant *entity.Tenant) (*entity.Tenant, error)

	// CreateTx creates a tenant within an existing transaction.
	// Used for atomic tenant+fee creation where the service layer manages the transaction.
	CreateTx(ctx context.Context, tx pgx.Tx, tenant *entity.Tenant) (*entity.Tenant, error)

	// FindByID returns a tenant by their UUID.
	// Returns sql.ErrNoRows when no tenant is found.
	FindByID(ctx context.Context, id string) (*entity.Tenant, error)

	// ListByTerritory returns all tenants in a given territory.
	// Results are ordered by block, then unit_number.
	ListByTerritory(ctx context.Context, territoryID string) ([]*entity.Tenant, error)

	// ListByUserID returns all tenants associated with a user through the user_tenants junction table.
	// Used for the resident role to scope access to their own tenants.
	ListByUserID(ctx context.Context, userID string) ([]*entity.Tenant, error)

	// Update updates an existing tenant's fields.
	// The territory_id is used as a guard to prevent cross-territory updates.
	// Returns sql.ErrNoRows when no tenant is found.
	Update(ctx context.Context, tenant *entity.Tenant) (*entity.Tenant, error)

	// Delete removes a tenant with territory scoping.
	// Returns sql.ErrNoRows when no tenant is found or the territory_id does not match.
	Delete(ctx context.Context, id string, territoryID string) error
}
