package repository

import (
	"context"

	"harmoni-api/internal/domain/entity"
)

// UserRepository defines the interface for user data access.
type UserRepository interface {
	// Create inserts a new user into the database.
	// The ID is generated by PostgreSQL's uuidv7() function.
	Create(ctx context.Context, user *entity.User) (*entity.User, error)

	// FindByEmail returns a user by their email address.
	// Returns sql.ErrNoRows when no user is found.
	FindByEmail(ctx context.Context, email string) (*entity.User, error)

	// FindByID returns a user by their UUID.
	// Returns sql.ErrNoRows when no user is found.
	FindByID(ctx context.Context, id string) (*entity.User, error)

	// UpdatePassword updates the password hash for a user.
	UpdatePassword(ctx context.Context, id, passwordHash string) error

	// ListByTerritory returns all users belonging to a specific territory.
	ListByTerritory(ctx context.Context, territoryID string) ([]*entity.User, error)
}
