package repository

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"harmoni-api/internal/domain/entity"
	"harmoni-api/internal/domain/repository"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/shopspring/decimal"
)

// Compile-time interface assertion.
var _ repository.TenantRepository = (*PostgresTenantRepository)(nil)

// PostgresTenantRepository implements repository.TenantRepository using PostgreSQL via pgx.
type PostgresTenantRepository struct {
	pool *pgxpool.Pool
}

// NewPostgresTenantRepository creates a new tenant repository backed by PostgreSQL.
func NewPostgresTenantRepository(pool *pgxpool.Pool) *PostgresTenantRepository {
	return &PostgresTenantRepository{pool: pool}
}

// Create inserts a new tenant. The ID is generated by PostgreSQL's uuidv7().
func (r *PostgresTenantRepository) Create(ctx context.Context, tenant *entity.Tenant) (*entity.Tenant, error) {
	query := `
		INSERT INTO tenants (block, unit_number, occupancy, monthly_fee, territory_id)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING id, created_at, updated_at
	`

	err := r.pool.QueryRow(ctx, query,
		tenant.Block,
		tenant.UnitNumber,
		tenant.Occupancy,
		tenant.MonthlyFee,
		tenant.TerritoryID,
	).Scan(&tenant.ID, &tenant.CreatedAt, &tenant.UpdatedAt)

	if err != nil {
		return nil, fmt.Errorf("failed to create tenant: %w", err)
	}

	return tenant, nil
}

// CreateTx creates a tenant within an existing transaction.
func (r *PostgresTenantRepository) CreateTx(ctx context.Context, tx pgx.Tx, tenant *entity.Tenant) (*entity.Tenant, error) {
	query := `
		INSERT INTO tenants (block, unit_number, occupancy, monthly_fee, territory_id)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING id, created_at, updated_at
	`

	err := tx.QueryRow(ctx, query,
		tenant.Block,
		tenant.UnitNumber,
		tenant.Occupancy,
		tenant.MonthlyFee,
		tenant.TerritoryID,
	).Scan(&tenant.ID, &tenant.CreatedAt, &tenant.UpdatedAt)

	if err != nil {
		return nil, fmt.Errorf("failed to create tenant in transaction: %w", err)
	}

	return tenant, nil
}

// FindByID returns a tenant by ID. Returns sql.ErrNoRows if not found.
func (r *PostgresTenantRepository) FindByID(ctx context.Context, id string) (*entity.Tenant, error) {
	query := `
		SELECT id, block, unit_number, occupancy, monthly_fee, territory_id, created_at, updated_at
		FROM tenants
		WHERE id = $1
	`

	tenant, err := scanTenant(r.pool.QueryRow(ctx, query, id))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, fmt.Errorf("failed to find tenant by ID: %w", err)
	}

	return tenant, nil
}

// ListByTerritory returns all tenants in a given territory.
func (r *PostgresTenantRepository) ListByTerritory(ctx context.Context, territoryID string) ([]*entity.Tenant, error) {
	query := `
		SELECT id, block, unit_number, occupancy, monthly_fee, territory_id, created_at, updated_at
		FROM tenants
		WHERE territory_id = $1
		ORDER BY block, unit_number
	`

	rows, err := r.pool.Query(ctx, query, territoryID)
	if err != nil {
		return nil, fmt.Errorf("failed to list tenants by territory: %w", err)
	}
	defer rows.Close()

	var tenants []*entity.Tenant
	for rows.Next() {
		tenant, err := scanTenantFromRow(rows)
		if err != nil {
			return nil, fmt.Errorf("failed to scan tenant row: %w", err)
		}
		tenants = append(tenants, tenant)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating tenant rows: %w", err)
	}

	return tenants, nil
}

// ListByUserID returns all tenants associated with a user through user_tenants.
func (r *PostgresTenantRepository) ListByUserID(ctx context.Context, userID string) ([]*entity.Tenant, error) {
	query := `
		SELECT t.id, t.block, t.unit_number, t.occupancy, t.monthly_fee, t.territory_id, t.created_at, t.updated_at
		FROM tenants t
		JOIN user_tenants ut ON t.id = ut.tenant_id
		WHERE ut.user_id = $1
		ORDER BY t.block, t.unit_number
	`

	rows, err := r.pool.Query(ctx, query, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to list tenants by user ID: %w", err)
	}
	defer rows.Close()

	var tenants []*entity.Tenant
	for rows.Next() {
		tenant, err := scanTenantFromRow(rows)
		if err != nil {
			return nil, fmt.Errorf("failed to scan tenant row: %w", err)
		}
		tenants = append(tenants, tenant)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating tenant rows: %w", err)
	}

	return tenants, nil
}

// Update updates an existing tenant. Returns sql.ErrNoRows if not found or territory_id mismatch.
func (r *PostgresTenantRepository) Update(ctx context.Context, tenant *entity.Tenant) (*entity.Tenant, error) {
	query := `
		UPDATE tenants
		SET block = $2, unit_number = $3, occupancy = $4, monthly_fee = $5, updated_at = NOW()
		WHERE id = $1 AND territory_id = $6
		RETURNING id, block, unit_number, occupancy, monthly_fee, territory_id, created_at, updated_at
	`

	updated, err := scanTenant(r.pool.QueryRow(ctx, query,
		tenant.ID,
		tenant.Block,
		tenant.UnitNumber,
		tenant.Occupancy,
		tenant.MonthlyFee,
		tenant.TerritoryID,
	))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, fmt.Errorf("failed to update tenant: %w", err)
	}

	return updated, nil
}

// Delete removes a tenant with territory scoping. Returns sql.ErrNoRows if not found.
func (r *PostgresTenantRepository) Delete(ctx context.Context, id string, territoryID string) error {
	query := `DELETE FROM tenants WHERE id = $1 AND territory_id = $2`

	result, err := r.pool.Exec(ctx, query, id, territoryID)
	if err != nil {
		return fmt.Errorf("failed to delete tenant: %w", err)
	}

	if result.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

// scanTenant scans a single tenant row from QueryRow.
func scanTenant(row pgx.Row) (*entity.Tenant, error) {
	tenant := &entity.Tenant{}
	var monthlyFee pgtype.Numeric

	err := row.Scan(
		&tenant.ID,
		&tenant.Block,
		&tenant.UnitNumber,
		&tenant.Occupancy,
		&monthlyFee,
		&tenant.TerritoryID,
		&tenant.CreatedAt,
		&tenant.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}

	dec, err := numericToDecimal(monthlyFee)
	if err != nil {
		return nil, fmt.Errorf("failed to decode monthly_fee: %w", err)
	}
	tenant.MonthlyFee = dec

	return tenant, nil
}

// scanTenantFromRow scans a single tenant from a multi-row result set.
func scanTenantFromRow(rows pgx.Rows) (*entity.Tenant, error) {
	tenant := &entity.Tenant{}
	var monthlyFee pgtype.Numeric

	err := rows.Scan(
		&tenant.ID,
		&tenant.Block,
		&tenant.UnitNumber,
		&tenant.Occupancy,
		&monthlyFee,
		&tenant.TerritoryID,
		&tenant.CreatedAt,
		&tenant.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}

	dec, err := numericToDecimal(monthlyFee)
	if err != nil {
		return nil, fmt.Errorf("failed to decode monthly_fee: %w", err)
	}
	tenant.MonthlyFee = dec

	return tenant, nil
}

// numericToDecimal converts a pgtype.Numeric to a decimal.Decimal.
func numericToDecimal(n pgtype.Numeric) (decimal.Decimal, error) {
	if !n.Valid {
		return decimal.Zero, nil
	}

	f64, err := n.Float64Value()
	if err != nil {
		return decimal.Zero, err
	}

	return decimal.NewFromFloat(f64.Float64), nil
}
